### ISSUE TITLE
update alpine image?

### ISSUE THREAD

**Issue by evo-ksalter** [b4tman/docker-squid#84]
I was wondering if there were any plans to use an updated alpine image any time soon.  We are using the 5.7 image, and scans show vulnerabilities.  Or if you have any recommendations to deal with them.  Thanks in advance.

**Comment by b4tman** [comment]
Hi @evo-ksalter!
Sorry for late reply.

I rebuild `latest` images only on @dependabot or `squid` version updates.
Tags/releases images only build one time on version update.
There is no scheduled builds configured yet due to very long build time (`qemu` used to for multiarch images).

So i recommend to build image at your own for your hardware architecture, when it possible. If you want latest base `alpine` images.
